apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xclusters.xcloud.io
  annotations:
    upbound.io/ui-schema: |-
      ---
      configSections:
      - title: Cluster Info
        description: Information about this cluster
        items:
        - name: id
          controlType: singleInput
          type: string
          path: ".spec.id"
          title: Cluster ID
          description: Cluster ID that other objects will use to refer to this cluster
          validation:
          - required: true
            customError: Cluster ID is required.
        - name: type
          controlType: singleSelect
          path: ".spec.compositionRef.name"
          title: Cluster type
          description: The type of the cluster
          enum:
          - cluster-aws
          - cluster-azure
          - cluster-google
          validation:
          - required: true
            customError: Cluster type is required.
      - title: Cluster Nodes
        description: Enter information to size your cluster
        items:
        - name: version
          controlType: singleInput
          type: string
          path: ".spec.parameters.version"
          title: Kubernetes version
          description: One of the versions supported by the vendor
          validation:
          - required: false
        - name: nodeSize
          controlType: singleSelect
          path: ".spec.parameters.nodeSize"
          title: Node Size
          description: Can be small, medium, or large. The specific size is determined by the vendor.
          enum:
          - small
          - medium
          - large
          validation:
          - required: true
            customError: Node size is required.
        - name: minNodeCount
          controlType: singleInput
          type: integer
          path: ".spec.parameters.minNodeCount"
          title: Minimum Node Count
          description: The minimum number of nodes. The number of the nodes might be bigger due to cluster autoscaler.
          default: 1
          validation:
          - minimum: 1
          - maximum: 10
          - required: false
spec:
  connectionSecretKeys:
    - kubeconfig
  defaultCompositionRef:
    name: xcloud-eks
  group: xcloud.io
  names:
    kind: XCluster
    plural: xclusters
  claimNames:
    kind: ClusterClaim
    plural: clusterclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: |-
                ---
                configSections:
                - title: Cluster Info
                  description: Information about this cluster
                  items:
                  - name: id
                    controlType: singleInput
                    type: string
                    path: ".spec.id"
                    title: Cluster ID
                    description: Cluster ID that other objects will use to refer to this cluster
                    validation:
                    - required: true
                      customError: Cluster ID is required.
                  - name: type
                    controlType: singleSelect
                    path: ".spec.compositionRef.name"
                    title: Cluster type
                    description: The type of the cluster
                    enum:
                    - cluster-aws
                    - cluster-azure
                    - cluster-google
                    validation:
                    - required: true
                      customError: Cluster type is required.
                - title: Cluster Nodes
                  description: Enter information to size your cluster
                  items:
                  - name: version
                    controlType: singleInput
                    type: string
                    path: ".spec.parameters.version"
                    title: Kubernetes version
                    description: One of the versions supported by the vendor
                    validation:
                    - required: false
                  - name: nodeSize
                    controlType: singleSelect
                    path: ".spec.parameters.nodeSize"
                    title: Node Size
                    description: Can be small, medium, or large. The specific size is determined by the vendor.
                    enum:
                    - small
                    - medium
                    - large
                    validation:
                    - required: true
                      customError: Node size is required.
                  - name: minNodeCount
                    controlType: singleInput
                    type: integer
                    path: ".spec.parameters.minNodeCount"
                    title: Minimum Node Count
                    description: The minimum number of nodes. The number of the nodes might be bigger due to cluster autoscaler.
                    default: 1
                    validation:
                    - minimum: 1
                    - maximum: 10
                    - required: false
              type: object
              properties:
                id:
                  type: string
                  description: ID of this Cluster that other objects will use to refer to it.
                parameters:
                  type: object
                  properties:
                    region:
                      description: The region for the cluster.
                      type: string
                    version:
                      description: The Kubernetes version for the cluster.
                      type: string
                    nodeSize:
                      description: The size of the nodes; small, medium, large
                      type: string
                    minNodeCount:
                      description: The minimum number of nodes
                      type: integer
                      default: 1
                    providerConfigName: 
                      description: The size of the nodes; small, medium, large
                      type: string
                      default: default

                  required:
                    - nodeSize
              required:
                - id
                - parameters
            status:
              type: object
              properties:
                clusterName:
                  description: The name of the cluster
                  type: string
                controlPlaneStatus:
                  description: The status of the control plane
                  type: string
                nodePoolStatus:
                  description: The status of the node pool
                  type: string
                # eks:
                #   description: Freeform field containing status information for eks
                #   type: object
                #   x-kubernetes-preserve-unknown-fields: true
                routetable:
                  type: boolean
                oidcIssuerUrl:
                  type: string
                oidcEKS:
                  type: string
                accountID:
                  type: string
                roleArnCSI:
                  type: string
      additionalPrinterColumns:
        - name: clusterName
          type: string
          jsonPath: ".status.clusterName"
        - name: controlPlane
          type: string
          jsonPath: ".status.controlPlaneStatus"
        - name: nodePool
          type: string
          jsonPath: ".status.nodePoolStatus"
