apiVersion: v1
kind: Secret
metadata:
  namespace: argocd
  creationTimestamp: null
  name: codecommit-creds
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Sir-gits-a-lot/crossplane-demo